name: parks_connect
description: Hybrid Parks Connect mobile app for tourists and field staff.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  http_parser: ^4.0.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3
  path_provider: ^2.1.4
  geolocator: ^12.0.0
  image_picker: ^1.1.2
  connectivity_plus: ^6.0.3
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
