/*
Audit summary
Existing Features:
- JWT-authenticated backend with role-based access for authority admins, environment officers, and tourism operators.
- Existing visitor, environmental, incident, feedback, alert, notification, reporting, and dashboard routes.
- Existing mobile feedback + incident submission and seeded demo data.
- Existing web login and dashboard experience with exports and park assignment support.

Missing Features:
- Unified feedback schema fields required by the brief: category, channel, visit_date, updated_at, and public/email ingestion support.
- Public web feedback page at /feedback and backend email feedback endpoint.
- Management alert API semantics required by the brief, including summary_text, triggered_at, manager email targeting, and daily capacity fields on parks.
- Dashboard-oriented feedback filtering/export fields and auto-refresh support data.

Partial Features:
- Alerts exist but currently use legacy severity/status semantics and are partly triggered during normal API requests.
- Analytics dashboard exists but does not yet expose the requested KPI/filter/chart dataset.
- README and automated backend tests do not yet cover the required objectives.
*/
import { getDb, closeDb } from './db.js';

const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('authority_admin','environment_officer','tourism_operator','tourist')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );`,
  `CREATE TABLE IF NOT EXISTS parks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    code TEXT UNIQUE,
    region TEXT,
    manager_email TEXT,
    daily_capacity_limit INTEGER NOT NULL DEFAULT 100,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );`,
  `CREATE TABLE IF NOT EXISTS park_assignments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    park_id INTEGER NOT NULL REFERENCES parks(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('authority_admin','environment_officer','tourism_operator')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, park_id)
  );`,
  `CREATE TABLE IF NOT EXISTS visitor_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    park_id INTEGER REFERENCES parks(id) ON DELETE SET NULL,
    operator_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    visit_date DATE NOT NULL,
    log_date DATE,
    visitors_count INTEGER NOT NULL DEFAULT 0,
    local_visitors INTEGER NOT NULL DEFAULT 0,
    international_visitors INTEGER NOT NULL DEFAULT 0,
    units_available INTEGER NOT NULL DEFAULT 0,
    units_occupied INTEGER NOT NULL DEFAULT 0,
    occupancy_rate NUMERIC(6,4),
    facility_feedback TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );`,
  `CREATE TABLE IF NOT EXISTS occupancy_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    park_id INTEGER NOT NULL REFERENCES parks(id) ON DELETE CASCADE,
    operator_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    log_date DATE NOT NULL,
    units_available INTEGER NOT NULL DEFAULT 0,
    units_occupied INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );`,
  `CREATE TABLE IF NOT EXISTS environmental_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    park_id INTEGER REFERENCES parks(id) ON DELETE SET NULL,
    staff_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    incident_type TEXT,
    event_type TEXT,
    severity TEXT,
    status TEXT NOT NULL DEFAULT 'new',
    location_lat NUMERIC(10,6),
    location_lng NUMERIC(10,6),
    photo_path TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );`,
  `CREATE TABLE IF NOT EXISTS feedback (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    park_id INTEGER REFERENCES parks(id) ON DELETE SET NULL,
    submitted_by TEXT,
    type TEXT NOT NULL CHECK (type IN ('tourist','operator','tourism_operator')),
    category TEXT,
    rating INTEGER,
    comments TEXT NOT NULL,
    channel TEXT,
    visit_date DATE,
    gps_lat NUMERIC(10,6),
    gps_lng NUMERIC(10,6),
    photo_path TEXT,
    device_id TEXT,
    source_email TEXT,
    status TEXT NOT NULL DEFAULT 'new',
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );`,
  `CREATE TABLE IF NOT EXISTS tourist_feedback (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_feedback_id INTEGER UNIQUE,
    park_id INTEGER REFERENCES parks(id) ON DELETE SET NULL,
    submitted_by TEXT,
    type TEXT NOT NULL CHECK (type IN ('tourist','tourism_operator')),
    category TEXT NOT NULL DEFAULT 'general',
    rating INTEGER CHECK (rating BETWEEN 1 AND 5),
    comments TEXT NOT NULL,
    channel TEXT NOT NULL DEFAULT 'mobile',
    visit_date DATE,
    gps_lat NUMERIC(10,6),
    gps_lng NUMERIC(10,6),
    photo_path TEXT,
    device_id TEXT,
    source_email TEXT,
    status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new','assigned','in_progress','resolved','escalated')),
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );`,
  `CREATE TABLE IF NOT EXISTS incidents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    park_id INTEGER NOT NULL REFERENCES parks(id) ON DELETE CASCADE,
    incident_type TEXT NOT NULL,
    description TEXT,
    severity TEXT NOT NULL DEFAULT 'medium' CHECK (severity IN ('low','medium','high','critical')),
    status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new','assigned','in_progress','resolved','escalated')),
    gps_lat NUMERIC(10,6),
    gps_lng NUMERIC(10,6),
    photo_path TEXT,
    device_id TEXT,
    duplicate_of INTEGER REFERENCES incidents(id) ON DELETE SET NULL,
    reported_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    reported_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );`,
  `CREATE TABLE IF NOT EXISTS alerts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    park_id INTEGER REFERENCES parks(id) ON DELETE SET NULL,
    source_type TEXT,
    source_id INTEGER,
    alert_type TEXT NOT NULL,
    message TEXT NOT NULL,
    summary_text TEXT,
    severity_level TEXT,
    alert_status TEXT,
    triggered_at TIMESTAMPTZ,
    severity TEXT NOT NULL DEFAULT 'warning' CHECK (severity IN ('info','warning','critical')),
    status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new','assigned','in_progress','resolved','escalated')),
    escalation_state TEXT NOT NULL DEFAULT 'none',
    due_at TIMESTAMPTZ,
    escalated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );`,
  `CREATE TABLE IF NOT EXISTS notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    park_id INTEGER REFERENCES parks(id) ON DELETE SET NULL,
    type TEXT NOT NULL,
    message TEXT NOT NULL,
    severity TEXT DEFAULT 'info',
    resolved BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );`,
  `CREATE TABLE IF NOT EXISTS alert_thresholds (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    park_id INTEGER REFERENCES parks(id) ON DELETE CASCADE,
    metric TEXT NOT NULL,
    threshold NUMERIC(12,4) NOT NULL,
    comparator TEXT NOT NULL DEFAULT '>',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );`,
  `CREATE TABLE IF NOT EXISTS facility_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );`,
  `CREATE TABLE IF NOT EXISTS facilities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    park_id INTEGER NOT NULL REFERENCES parks(id) ON DELETE CASCADE,
    facility_type_id INTEGER NOT NULL REFERENCES facility_types(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    units_available INTEGER NOT NULL DEFAULT 0,
    units_occupied INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive','maintenance')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );`,
  `CREATE TABLE IF NOT EXISTS report_exports (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    park_id INTEGER REFERENCES parks(id) ON DELETE SET NULL,
    report_type TEXT NOT NULL,
    file_path TEXT NOT NULL,
    file_url TEXT NOT NULL,
    generated_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );`,
  `CREATE TABLE IF NOT EXISTS blockchain_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_type TEXT NOT NULL,
    record_id TEXT NOT NULL UNIQUE,
    data_hash TEXT NOT NULL,
    tx_hash TEXT,
    block_number BIGINT,
    status TEXT NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );`,
  `CREATE INDEX IF NOT EXISTS idx_park_assignments_user_park ON park_assignments(user_id, park_id);`,
  `CREATE INDEX IF NOT EXISTS idx_visitor_logs_park_log_date ON visitor_logs(park_id, log_date);`,
  `CREATE INDEX IF NOT EXISTS idx_occupancy_logs_park_log_date ON occupancy_logs(park_id, log_date);`,
  `CREATE INDEX IF NOT EXISTS idx_tourist_feedback_park_submitted_at ON tourist_feedback(park_id, submitted_at);`,
  `CREATE INDEX IF NOT EXISTS idx_incidents_park_reported_status ON incidents(park_id, reported_at, status);`,
  `CREATE INDEX IF NOT EXISTS idx_alerts_park_created_status ON alerts(park_id, created_at, status);`,
  `CREATE INDEX IF NOT EXISTS idx_alerts_due_status ON alerts(status, due_at);`,
  `CREATE INDEX IF NOT EXISTS idx_blockchain_records_type_status ON blockchain_records(record_type, status);`
];

const dataMaintenanceStatements = [
  `DELETE FROM alert_thresholds current_threshold
   USING alert_thresholds newer_threshold
   WHERE COALESCE(current_threshold.park_id, -1) = COALESCE(newer_threshold.park_id, -1)
     AND current_threshold.metric = newer_threshold.metric
     AND current_threshold.id < newer_threshold.id;`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_alert_thresholds_unique_scope_metric
   ON alert_thresholds ((COALESCE(park_id, -1)), metric);`,
  `ALTER TABLE parks ADD COLUMN IF NOT EXISTS manager_email TEXT;`,
  `ALTER TABLE parks ADD COLUMN IF NOT EXISTS daily_capacity_limit INTEGER NOT NULL DEFAULT 100;`,
  `ALTER TABLE feedback ADD COLUMN IF NOT EXISTS category TEXT;`,
  `ALTER TABLE feedback ADD COLUMN IF NOT EXISTS channel TEXT;`,
  `ALTER TABLE feedback ADD COLUMN IF NOT EXISTS visit_date DATE;`,
  `ALTER TABLE feedback ADD COLUMN IF NOT EXISTS source_email TEXT;`,
  `ALTER TABLE feedback ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();`,
  `ALTER TABLE tourist_feedback ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'general';`,
  `ALTER TABLE tourist_feedback ADD COLUMN IF NOT EXISTS channel TEXT NOT NULL DEFAULT 'mobile';`,
  `ALTER TABLE tourist_feedback ADD COLUMN IF NOT EXISTS visit_date DATE;`,
  `ALTER TABLE tourist_feedback ADD COLUMN IF NOT EXISTS source_email TEXT;`,
  `ALTER TABLE tourist_feedback ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();`,
  `ALTER TABLE alerts ADD COLUMN IF NOT EXISTS summary_text TEXT;`,
  `ALTER TABLE alerts ADD COLUMN IF NOT EXISTS severity_level TEXT;`,
  `ALTER TABLE alerts ADD COLUMN IF NOT EXISTS alert_status TEXT;`,
  `ALTER TABLE alerts ADD COLUMN IF NOT EXISTS triggered_at TIMESTAMPTZ;`,
  `UPDATE feedback
   SET channel = COALESCE(channel, CASE WHEN device_id IS NOT NULL THEN 'mobile' ELSE 'web' END),
       category = COALESCE(category, 'general'),
       visit_date = COALESCE(visit_date, submitted_at::date),
       updated_at = COALESCE(updated_at, created_at);`,
  `UPDATE tourist_feedback
   SET channel = COALESCE(channel, CASE WHEN device_id IS NOT NULL THEN 'mobile' ELSE 'web' END),
       category = COALESCE(category, 'general'),
       visit_date = COALESCE(visit_date, submitted_at::date),
       updated_at = COALESCE(updated_at, created_at);`,
  `UPDATE alerts
   SET summary_text = COALESCE(summary_text, message),
       severity_level = COALESCE(
         severity_level,
         CASE severity
           WHEN 'critical' THEN 'critical'
           WHEN 'warning' THEN 'high'
           ELSE 'medium'
         END
       ),
       alert_status = COALESCE(
         alert_status,
         CASE status
           WHEN 'resolved' THEN 'resolved'
           WHEN 'assigned' THEN 'acknowledged'
           WHEN 'in_progress' THEN 'acknowledged'
           WHEN 'escalated' THEN 'acknowledged'
           ELSE 'open'
       END
       ),
       triggered_at = COALESCE(triggered_at, created_at);`,
  `CREATE INDEX IF NOT EXISTS idx_tourist_feedback_channel_category ON tourist_feedback(channel, category);`,
  `CREATE INDEX IF NOT EXISTS idx_alerts_alert_status_triggered ON alerts(alert_status, triggered_at);`
];

async function seedDefaultThresholds(db) {
  const thresholds = [
    { metric: 'visitors', threshold: 500, comparator: '>' },
    { metric: 'occupancy', threshold: 0.85, comparator: '>' },
    { metric: 'rating_drop_7d', threshold: 3, comparator: '<' },
    { metric: 'incident_high', threshold: 1, comparator: '>=' }
  ];

  for (const threshold of thresholds) {
    const existing = await db.get(
      `SELECT id FROM alert_thresholds WHERE park_id IS NULL AND metric = ?`,
      [threshold.metric]
    );

    if (!existing) {
      await db.run(
        `INSERT INTO alert_thresholds (park_id, metric, threshold, comparator)
         VALUES (NULL, ?, ?, ?)`,
        [threshold.metric, threshold.threshold, threshold.comparator]
      );
    }
  }
}

export async function runMigrations() {
  const db = await getDb();

  for (const sql of schemaStatements) {
    await db.exec(sql);
  }

  for (const sql of dataMaintenanceStatements) {
    await db.exec(sql);
  }

  await seedDefaultThresholds(db);
}

if (process.argv[1] && process.argv[1].includes('migrate.js')) {
  runMigrations()
    .then(() => {
      console.log('Migrations completed.');
    })
    .catch((err) => {
      console.error('Migration failed', err);
      process.exitCode = 1;
    })
    .finally(async () => {
      await closeDb();
    });
}
